services:
  - type: web
    name: the-system-solo-leveling
    runtime: docker
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_ALLOWED_USER_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
